---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_stages: [commit]

repos:
  # Standard hooks to fix up file
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: fix-encoding-pragma
      - id: trailing-whitespace # Trim whitespace from end of each line
      - id: end-of-file-fixer # All files only end in newline
      - id: check-yaml # verify yaml syntax
        args: [--allow-multiple-documents]
      - id: check-added-large-files # prevent extremely large files from being committed
        args: [--maxkb=10000]
      - id: mixed-line-ending # force linux line endings
        args: [--fix=lf]
      - id: check-ast # validates python files
      - id: check-merge-conflict # prevent merge conflict strings
      - id: check-case-conflict # prevent file namings that would fail on case insensitive file systems
      - id: check-docstring-first # checks a common error of defining a docstring after code
      - id: check-toml # validates toml files
      - id: debug-statements # validates there are no debugger imports
      - id: detect-private-key
      - id: name-tests-test # ensures test files are named correclty
        args: [--pytest-test-first]
      - id: check-json
      # - id: pretty-format-json
      # args: [--autofix]
      - id: check-shebang-scripts-are-executable

  # Use prettier to format files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4" # Use the sha / tag you want to point at
    hooks:
      - id: prettier

  # Check for common spelling errors
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        args: [-w]
        exclude: inputs

  # Remove unused imports and code
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.8
    hooks:
      - id: autoflake
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --remove-unused-variables,
            --expand-star-imports,
            --ignore-init-module-imports,
          ]
        types: [python]
        stages: [commit]
        exclude: docs

  # Deterministically fix imports
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile, black]
        types: [python]
        stages: [commit]
        exclude: docs

  # Define python format
  - repo: https://github.com/psf/black
    rev: 22.10.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
        types: [python]
        stages: [commit]
        exclude: docs

  # Fix markdown lints
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint-fix
        args: ["--fix", "--config", "markdownlintrc.ini"]
